version: '3.0'
services:
  
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: '12345'
    ports:
      - "3308:3306"
      
    volumes:
      - mysql-data:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - "8082:8080"

volumes:
  mysql-data: